<a href="https://colab.research.google.com/github/HyojinKim88/ML-for-AI/blob/main/week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
cd /content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition

# task 1

In [2]:
import pandas as pd

In [4]:
data = pd.read_csv("ch_02/data/earthquakes.csv")

In [14]:
data.head(2)

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...

In [13]:
data.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [9]:
data.loc[3:10,['mag', 'magType', 'type']]

     mag magType        type
3   0.44      ml  earthquake
4   2.16      md  earthquake
5   2.61      md  earthquake
6   1.70      ml  earthquake
7   1.13      md  earthquake
8   0.92      md  earthquake
9   4.70      mb  earthquake
10  0.50      ml  earthquake

In [16]:
data.loc[(data.place.str.contains("Arizona")),['mag', 'magType', 'type']]

       mag magType        type
1062  1.23      ml  earthquake
3965  0.94      md  earthquake

In [17]:
data.mag.nlargest(10, keep='all')

5263    7.5
837     7.0
118     6.7
4363    6.7
799     6.5
816     6.2
838     6.1
5323    6.1
862     6.0
1267    6.0
3699    6.0
9211    6.0
Name: mag, dtype: float64

In [18]:
data.nlargest(10,['mag'])

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
5263,red,8.4,1000h3p4,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.589,18.0,27.0,",us1000h3p4,us1000h4p4,",7.5,mww,...,",us,us,",reviewed,1538128963480,"M 7.5 - 78km N of Palu, Indonesia",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",480.0,1539123134531,https://earthquake.usgs.gov/earthquakes/eventp...
837,green,4.1,1000haa3,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.763,3.0,14.0,",us1000haa3,pt18283003,at00pgehsk,",7.0,mww,...,",us,pt,at,",reviewed,1539204500290,"M 7.0 - 117km E of Kimbe, Papua New Guinea",1,earthquake,",dyfi,finite-fault,general-text,geoserve,groun...",600.0,1539378744253,https://earthquake.usgs.gov/earthquakes/eventp...
118,green,NaN,1000hbkz,https://earthquake.usgs.gov/fdsnws/event/1/que...,2.623,NaN,25.0,",pt18286001,at00pgjb1a,us1000hbkz,",6.7,mww,...,",pt,at,us,",reviewed,1539429023560,"M 6.7 - 262km NW of Ozernovskiy, Russia",1,earthquake,",geoserve,ground-failure,impact-link,losspager...",600.0,1539455437040,https://earthquake.usgs.gov/earthquakes/eventp...
4363,green,2.2,1000h4l1,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.728,1.0,23.0,",at00pfv7ja,us1000h4l1,pt18273000,",6.7,mww,...,",at,us,pt,",reviewed,1538304744240,"M 6.7 - 263km NNE of Ndoi Island, Fiji",1,earthquake,",dyfi,geoserve,impact-link,losspager,moment-te...",-720.0,1539348741510,https://earthquake.usgs.gov/earthquakes/eventp...
799,green,NaN,1000hacw,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.879,NaN,18.0,",pt18283004,at00pgeomo,us1000hacw,",6.5,mww,...,",pt,at,us,",reviewed,1539213362130,"M 6.5 - 148km S of Severo-Kuril'sk, Russia",1,earthquake,",geoserve,ground-failure,impact-link,losspager...",600.0,1539224915040,https://earthquake.usgs.gov/earthquakes/eventp...
816,green,NaN,1000habl,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.907,NaN,12.0,",us1000habl,",6.2,mww,...,",us,",reviewed,1539208835130,"M 6.2 - 94km SW of Kokopo, Papua New Guinea",1,earthquake,",geoserve,ground-failure,losspager,moment-tens...",600.0,1539219109963,https://earthquake.usgs.gov/earthquakes/eventp...
838,green,NaN,1000ha9t,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.757,NaN,18.0,",us1000ha9t,",6.1,mb,...,",us,",reviewed,1539204326420,"M 6.1 - 132km E of Kimbe, Papua New Guinea",1,earthquake,",geoserve,ground-failure,losspager,origin,phas...",600.0,1539217505598,https://earthquake.usgs.gov/earthquakes/eventp...
5323,green,NaN,1000h3mf,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.812,NaN,33.0,",us1000h3mf,",6.1,mww,...,",us,",reviewed,1538118001950,"M 6.1 - 55km NNW of Palu, Indonesia",1,earthquake,",geoserve,ground-failure,losspager,moment-tens...",480.0,1538158590933,https://earthquake.usgs.gov/earthquakes/eventp...
862,green,4.3,1000ha6q,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.051,170.0,27.0,",us1000ha6q,",6.0,mww,...,",us,",reviewed,1539197095310,"M 6.0 - 39km NNE of Sumberanyar, Indonesia",0,earthquake,",dyfi,geoserve,ground-failure,losspager,moment...",480.0,1539515759040,https://earthquake.usgs.gov/earthquakes/eventp...
1267,green,NaN,1000h97j,https://earthquake.usgs.gov/fdsnws/event/1/que...,3.806,NaN,92.0,",us1000h97j,",6.0,mww,...,",us,",reviewed,1539071114670,"M 6.0 - 138km S of Severo-Kuril'sk, Russia",0,earthquake,",geoserve,ground-failure,losspager,moment-tens...",600.0,1539213313361,https://earthquake.usgs.gov/earthquakes/eventp...

# task2

Tasks for today 2-Try to pop mag and magTypevariables one at a time with name mag, and magType. (use .pop function)-Concatenate mag and magTypevariables and define a new DataFrameusing .concatfunction

In [20]:
del data['alert']

In [21]:
mag = data.pop('mag')
magtype = data.pop('magType')

In [29]:
newdata = pd.concat([mag,magtype])
newdata

0       1.35
1       1.29
2       3.42
3       0.44
4       2.16
        ...
9327      md
9328      ml
9329      md
9330      ml
9331      ml
Length: 18664, dtype: object